### ISSUE TITLE
Renaming 'Complaint' module

### ISSUE THREAD

**Issue by jj1161** [ArkCase/arkcase-ce#370]
Using the Labels configuration in the admin site it is possible to change the name of 'Complaints' module to 'Investigations' in top menu and left menu. 
Is it also possible to change the names of the documents generated within the complaint in the Documents folder?
Here is what I'm referring to, I would like to change the document name 'Complaint' to 'Investigation':
![image](https://user-images.githubusercontent.com/96937598/149326794-6d6ada0c-4a56-460c-ae03-cb0220664f03.png)

And also as they appear in a Case that is opened for this complaint including the folder name:

![image](https://user-images.githubusercontent.com/96937598/149326947-3cad53dd-b841-41dd-879d-5676f64cddbb.png)

An additional question - does arkcase-ce support updating only the war file so that it is possible to take a new ArkCase release without losing all the configuration changes in the VM?
Thanks

**Comment by mmaines** [comment]
jj1161,

The module labels can be change from Admin on the Label Configuration Page. There are  about 6-8,000 labels in the application.

![image](https://user-images.githubusercontent.com/12833327/149338193-892753ef-ab4d-43bd-a36c-a9e7284e747e.png)

As for changing the auto-generated pdf file, that is not a label and is in configuration.

**Comment by david-oc-miller** [comment]
@jj1161 ,

I wrote ticket https://arkcase.atlassian.net/browse/ACFP-1549 in order to make the Complaint.pdf file configurable.

At this moment the filename is defined in the class ComplaintConstants, constant COMPLAINT_FILENAMEFORMAT.  You can see ComplaintConstants also defines some other filenames.

If you were to checkout the code base and update ComplaintConstants.COMPLAINT_FILENAMEFORMAT to have the filename of your choice, and build a new arkcase.war, you can deploy this new arkcase.war in the VM like so:

- copy the updated arkcase.war to the VM
- vagrant ssh (to ssh into the VM)
- sudo systemctl stop arkcase
- sudo su - arkcase -s /bin/bash
- cd /opt/arkcase/app/arkcase
- mv webapps/arkcase.war arkcase.war.backup <-- keep a backup war file just in case
- rm -rf temp/*
- rm -rf /opt/arkcase/tmp/arkcase/*
- rm -rf work/*
- exit
- sudo systemctl start arkcase

--
Dave

**Comment by david-oc-miller** [comment]
@jj1161 ,

The folder name is defined in a Spring XML file.  You can override this in an ArkCase extension.  See https://arkcase.atlassian.net/wiki/spaces/AD/pages/1647738881/Tutorial+Extending+ArkCase for a detailed extension guide, and in the section https://arkcase.atlassian.net/wiki/spaces/AD/pages/1647738881/Tutorial+Extending+ArkCase#1.7------Extend-Complaint-Solr-Transformer you can see how to override a Spring bean.

The Spring bean in question is `complaintFolderNameFormat` defined in the file `spring-library-complaint.xml`.  

If you prefer you can change this bean value in the source code and rebuild and deploy the whole war file, as I described in my earlier comment.

I wrote ticket https://arkcase.atlassian.net/browse/ACFP-1550 to fix this issue.  We don't want people to have to recompile code or write an extension, just to change some string in the user interface.

**Comment by jj1161** [comment]
I made the 2 changes and it works good. The document and folder names have changed.
There is an additional change that is needed in CloseComplaintConstants, a file that is also auto-generated when closing a complaint.
Thanks for this information, it is very helpful.

**Comment by david-oc-miller** [comment]
Awesome, thanks.... In my instructions I forgot to mention copying the new arkcase.war into the proper place but obviously you figured it out.
