### ISSUE TITLE
Docker file instead of VirtualBox

### ISSUE THREAD

**Issue by dpieski** [ArkCase/arkcase-ce#8]
Are there any plans for a Docker image? 

I regularly use Hyper-V on my computer, which limits use of VT-x, therefor, I cannot use multicore processors on VirtualBox.

**Comment by david-oc-miller** [comment]
Hi Andrew,

There are plans for a Docker image; but before that I should have a Hyper-V-supported Vagrant box.  I am working on a Hyper-V Vagrant image now.  I will note back here when it is ready.

--
Dave

**Comment by mzimmerman** [comment]
I would also be interested in a docker container.  Is there a way I could help with this?

**Comment by dbl2** [comment]
Is there any update on the Hyper-V vagrant box?

**Comment by dpieski** [comment]
hi @david-oc-miller 
Is there any update on the HyperV box?

**Comment by david-oc-miller** [comment]
@dpieski, we supported a HyperV box internally for a short time, but abandoned it due to the effect Hyper-V has on wireless networking on Windows 10.  

All our efforts now are on an Amazon Marketplace AMI, which you can find here, https://aws.amazon.com/marketplace/search?searchTerms=arkcase.  For the foreseeable future this is by far the easiest way to get started, and we have a corporate commitment to update the Marketplace offering on each new ArkCase release.

We are working on a Kubernetes distribution, with Istio, monitoring, dashboards, and what not but it is still early days on this.

**Comment by david-oc-miller** [comment]
The container support is still in process.  Until now the Marketplace deployments are still the best way to try ArkCase: https://aws.amazon.com/marketplace/search?searchTerms=arkcase

**Comment by kemboi22** [comment]
Is the docker image still in progress

**Comment by satya-udayakumar** [comment]
Hi Elvis,

Please note that Docker support is no longer available for our software. We now offer installation through Helm charts and the AWS Marketplace.

For installation using Helm, please refer to our installation guide: https://github.com/ArkCase/ArkCase/blob/installation-guide-updateV2/README.md

To deploy using AWS Marketplace, visit our AWS Marketplace listing: https://aws.amazon.com/marketplace/pp/prodview-iow7wn3ygk4dw?sr=0-2&ref_=beagle&applicationId=AWSMPContessa

Thank you.

**Comment by kemboi22** [comment]
> Hi Elvis,
> 
> Please note that Docker support is no longer available for our software. We now offer installation through Helm charts and the AWS Marketplace.
> 
> For installation using Helm, please refer to our installation guide: https://github.com/ArkCase/ArkCase/blob/installation-guide-updateV2/README.md
> 
> To deploy using AWS Marketplace, visit our AWS Marketplace listing: https://aws.amazon.com/marketplace/pp/prodview-iow7wn3ygk4dw?sr=0-2&ref_=beagle&applicationId=AWSMPContessa
> 
> Thank you.

Okay i have tried to deploy helm charts on the server but it crashed i dont know why
I have used a v4 cpu , 16gb ram and 100 gb storage

Also curious to ask why is docker not supported or podman

Because i wanted to create a module that can work on nethserver https://www.nethserver.org/

**Comment by kemboi22** [comment]
So nethserver uses Systemd files to serve applications behind the scenes
So is this possible

**Comment by satya-udayakumar** [comment]
We have used Kubernetes features thats why we are using kubernetes instead of docker. Additionally, we do not support NethServer.

Regarding the issue you're facing with the Helm chart deployment, I'd be happy to assist you in troubleshooting. Please contact me at my work email: satya.udayakumar@armedia.com.

**Comment by kemboi22** [comment]
Okay
